[package]
name = "parallel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.3"
is_prime = "2.0.9"
log = "0.4.21"
num-bigint = "0.4.4"
num-traits = "0.2.18"
rayon = "1.9.0"
